//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegaiaText.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LegaiaText.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C100={Vahn}
        ///C101={Noa}
        ///C102={Gala}
        ///C103={Terra}
        ///C201={Ra-Seru Meta LV1}
        ///C202={Ra-Seru Meta LV2}
        ///C203={Ra-Seru Meta Lv3}
        ///C204={Ra-Seru Meta Lv4}
        ///C205={Ra-Seru Meta Lv5}
        ///C206={Ra-Seru Meta Lv6}
        ///C207={Ra-Seru Meta Lv7}
        ///C208={Ra-Seru Meta Lv8}
        ///C209={Ra-Seru Meta Lv9}
        ///C20A={Ra-Seru Terra Lv1}
        ///C20B={Ra-Seru Terra Lv2}
        ///C20C={Ra-Seru Terra Lv3}
        ///C20D={Ra-Seru Terra Lv4}
        ///C20E={Ra-Seru Terra Lv5}
        ///C20F={Ra-Seru Terra Lv6}
        ///C210={Ra-Seru Terra Lv7}
        ///C211={Ra-Seru Terra Lv8}
        ///C213={Ra-Seru Ozma Lv1}
        ///C2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
    }
}
